export const blogStats = {
  totalPosts: { label: "Total Posts", value: 147, change: "+12", icon: "FileText" },
  published: { label: "Published", value: 134, change: "+8", icon: "Eye" },
  drafts: { label: "Draft Posts", value: 13, change: "+4", icon: "Edit" },
  totalViews: { label: "Total Views", value: "45.2K", change: "+2.1K", icon: "TrendingUp" },
};

export const blogs = [
  {
    id: 1,
    title: "The Future of Music Distribution",
    author: "Sarah Johnson",
    category: "Industry News",
    status: "Published",
    createdAt: "2024-01-15",
    views: 1247,
    comments: 23,
    featured: true,
  },
  {
    id: 2,
    title: "How to Optimize Your Music for Streaming",
    author: "Mike Chen",
    category: "Tips & Guides",
    status: "Published",
    createdAt: "2024-01-12",
    views: 892,
    comments: 15,
    featured: false,
  },
  {
    id: 3,
    title: "New Features Coming to the Platform",
    author: "Admin Team",
    category: "Product Updates",
    status: "Draft",
    createdAt: null,
    views: 0,
    comments: 0,
    featured: false,
  },
  {
    id: 4,
    title: "Artist Spotlight: Rising Stars of 2024",
    author: "Emma Davis",
    category: "Artist Features",
    status: "Scheduled",
    createdAt: "2024-01-20",
    views: 0,
    comments: 0,
    featured: true,
  },
  {
    id: 5,
    title: "Understanding Music Copyright",
    author: "Legal Team",
    category: "Legal",
    status: "Published",
    createdAt: "2024-01-10",
    views: 2156,
    comments: 41,
    featured: false,
  },
];
