export const labels = [
  {
    id: "1",
    labelNo: "LBL001",
    label: "Maheshwari Music",
    designation: "Premium Music Label",
    artists: 45,
    releases: 120,
    monthlyStreams: 5500000,
    status: "Active",
    lastUpdated: "2024-03-15",
  },
  {
    id: "2",
    labelNo: "LBL002",
    label: "Classical Records",
    designation: "Traditional Music Label",
    artists: 28,
    releases: 85,
    monthlyStreams: 3200000,
    status: "Active",
    lastUpdated: "2024-03-12",
  },
  {
    id: "3",
    labelNo: "LBL003",
    label: "Folk Fusion",
    designation: "Regional Music Label",
    artists: 18,
    releases: 42,
    monthlyStreams: 1800000,
    status: "Inactive",
    lastUpdated: "2024-03-10",
  },
];
