export const mockSyncStats = [
  { key: "total", label: "Total Requests", value: 5 },
  { key: "pending", label: "Pending Review", value: 2 },
  { key: "approved", label: "Approved", value: 1 },
  { key: "licenseValue", label: "License Value", value: "₹75,000" },
];

// Mock table data
export const mockSyncRequests = [
  {
    id: 1,
    trackName: "Bollywood Romance",
    artistName: "Rajesh Kumar",
    labelName: "Rajesh Kumar",
    isrc: "Bollywood",
    genre: "Bollywood",
    mood: "Editorial",
    theme: "Love",
    language: "Bollywood",
    tempo: "Lorem",
    masterRights: "Artist",
    proAffiliation: "IPRS",
    projectSuitability: "Podcasts",
    submitDate: "2024-03-15",
    status: "Pending",
    projectName: "Mumbai Love Story",
    projectType: "Bollywood Film",
    licenseType: "Film",
    licenseValue: "₹150,000",
    territory: "India",
    duration: "3:45",
    startDate: "2024-04-01",
    endDate: "2024-12-31",
    contactEmail: "producer@mumbaifilm.com",
    usage: "Background score for romantic scenes",
    description: "Need sync license for romantic track in upcoming Bollywood film",
  },
  {
    id: 2,
    trackName: "Classical Raga Morning",
    artistName: "Pandit Ravi Shankar",
    labelName: "Pandit Ravi Shankar",
    isrc: "Classical",
    genre: "Classical",
    mood: "Genre-specific",
    theme: "Love",
    language: "--",
    tempo: "Lorem",
    masterRights: "Label",
    proAffiliation: "ASCAP",
    projectSuitability: "Podcasts",
    submitDate: "2024-03-12",
    status: "Pending",
    projectName: "Mumbai Love Story",
    projectType: "Bollywood Film",
    licenseType: "Film",
    licenseValue: "₹150,000",
    territory: "India",
    duration: "3:45",
    startDate: "2024-04-01",
    endDate: "2024-12-31",
    contactEmail: "producer@mumbaifilm.com",
    usage: "Background score for romantic scenes",
    description: "Need sync license for romantic track in upcoming Bollywood film",
  },
  {
    id: 3,
    trackName: "Modern Folk Fusion",
    artistName: "Sound Aggregators",
    labelName: "Sound Aggregators",
    isrc: "Folk",
    genre: "Folk",
    mood: "Featured",
    theme: "Love",
    language: "Bollywood",
    tempo: "Lorem",
    masterRights: "Label",
    proAffiliation: "IPRS",
    projectSuitability: "Ad Campaigns",
    submitDate: "2024-03-10",
    status: "Approved",
    projectName: "Mumbai Love Story",
    projectType: "Bollywood Film",
    licenseType: "Film",
    licenseValue: "₹150,000",
    territory: "India",
    duration: "3:45",
    startDate: "2024-04-01",
    endDate: "2024-12-31",
    contactEmail: "producer@mumbaifilm.com",
    usage: "Background score for romantic scenes",
    description: "Need sync license for romantic track in upcoming Bollywood film",
  },
  {
    id: 4,
    trackName: "Devotional Chant",
    artistName: "Maheshwari Music",
    labelName: "Maheshwari Music",
    isrc: "Devotional",
    genre: "Devotional",
    mood: "Editorial",
    theme: "Love",
    language: "Bollywood",
    tempo: "Lorem",
    masterRights: "Label",
    proAffiliation: "ASCAP",
    projectSuitability: "Podcasts",
    submitDate: "2024-03-08",
    status: "Approved",
    projectName: "Mumbai Love Story",
    projectType: "Bollywood Film",
    licenseType: "Film",
    licenseValue: "₹150,000",
    territory: "India",
    duration: "3:45",
    startDate: "2024-04-01",
    endDate: "2024-12-31",
    contactEmail: "producer@mumbaifilm.com",
    usage: "Background score for romantic scenes",
    description: "Need sync license for romantic track in upcoming Bollywood film",
  },
];
