export const mockTeamData = {
  totalMembers: 47,
  activeMembers: 43,
  pendingInvites: 4,
  avgResponseTime: "2.3h",
  avgResponseChange: "-0.5h improved",
  members: [
    {
      name: "Rajesh Kumar",
      email: "rajesh.kumar@maheshwarivisuals.com",
      role: "Admin",
      department: "Management",
      status: "Active",
      joinDate: "2023-01-15",
      lastActive: "2024-01-28",
    },
    {
      name: "Priya Sharma",
      email: "priya.sharma@maheshwarivisuals.com",
      role: "Content Manager",
      department: "Content",
      status: "Active",
      joinDate: "2023-03-22",
      lastActive: "2024-01-28",
    },
    {
      name: "Amit Patel",
      email: "amit.patel@maheshwarivisuals.com",
      role: "Developer",
      department: "Technology",
      status: "Active",
      joinDate: "2023-06-10",
      lastActive: "2024-01-27",
    },
    {
      name: "Sneha Gupta",
      email: "sneha.gupta@maheshwarivisuals.com",
      role: "Marketing Lead",
      department: "Marketing",
      status: "Away",
      joinDate: "2023-08-05",
      lastActive: "2024-01-25",
    },
    {
      name: "Vikram Singh",
      email: "vikram.singh@maheshwarivisuals.com",
      role: "Support Specialist",
      department: "Support",
      status: "Inactive",
      joinDate: "2023-11-12",
      lastActive: "2024-01-20",
    },
  ],
};
