// Mock data (shape kept API-friendly)
export const mockPitchStats = [
  { label: "Total Submissions", key: "total", value: 0, subtext: "" },
  { label: "Pending Review",   key: "pending", value: 0, subtext: "" },
  { label: "Approved",         key: "approved", value: 0, subtext: "" },
  { label: "Under Review",     key: "underReview", value: 0, subtext: "" },
];

export const mockPitches = [
  {
    id: "trk_001",
    trackName: "Bollywood Romance",
    artistName: "Rajesh Kumar",
    userId: "48298y892hf8392",
    isrc: "Bollywood",
    genre: "Bollywood",
    mood: "Editorial",         
    theme: "Love",
    language: "Bollywood",
    store: "Spotify",
    submitDate: "2024-03-15",
    status: "Pending Review",   
    type: "Single",
  },
  {
    id: "trk_002",
    trackName: "Classical Raga Morning",
    artistName: "Pandit Ravi Shankar",
    userId: "48298y892hf8392",
    isrc: "Classical",
    genre: "Classical",
    mood: "Genre-specific",
    theme: "Love",
    language: "--",
    store: "Spotify",
    submitDate: "2024-03-12",
    status: "Pending Review",
    type: "Album",
  },
  {
    id: "trk_003",
    trackName: "Modern Folk Fusion",
    artistName: "Sound Aggregators",
    userId: "48298y892hf8392",
    isrc: "Folk",
    genre: "Folk",
    mood: "Featured",
    theme: "Love",
    language: "Bollywood",
    store: "Spotify",
    submitDate: "2024-03-10",
    status: "Under Review",
    type: "Single",
  },
  {
    id: "trk_004",
    trackName: "Devotional Chant",
    artistName: "Maheshwari Music",
    userId: "48298y892hf8392",
    isrc: "Devotional",
    genre: "Devotional",
    mood: "Editorial",
    theme: "Love",
    language: "Bollywood",
    store: "Spotify",
    submitDate: "2024-03-08",
    status: "Pending Review",
    type: "EP",
  },
];
