export const faqs = [
  {
    id: 1,
    order: 1,
    question: "How do I upload my music to Maheshwari Visuals?",
    answer: "You can upload by navigating to the Upload section in your dashboard, selecting your files, and filling out required metadata.",
    category: "Upload Process",
    displayStatus: "On",
    status: "Published",
    createdAt: "2024-01-15",
    lastUpdated: "2024-03-10",
  },
  {
    id: 2,
    order: 2,
    question: "How long does it take for my music to go live on streaming platforms?",
    answer: "Typically, your music goes live within 5–7 business days after approval.",
    category: "Distribution",
    displayStatus: "On",
    status: "Published",
    createdAt: "2024-01-20",
    lastUpdated: "2024-02-15",
  },
  {
    id: 3,
    order: 3,
    question: "What percentage of royalties do I keep?",
    answer: "You keep 85% of the royalties, while the remaining 15% covers distribution and platform fees.",
    category: "Royalties",
    displayStatus: "On",
    status: "Published",
    createdAt: "2024-02-01",
    lastUpdated: "2024-02-25",
  },
  {
    id: 4,
    order: 4,
    question: "Can I edit my release after it’s been published?",
    answer: "Once published, release details can only be edited with admin approval to ensure data consistency.",
    category: "Release Management",
    displayStatus: "Off",
    status: "Draft",
    createdAt: "2024-02-10",
    lastUpdated: "2024-03-01",
  },
];
