export const testimonials = [
  {
    id: "1",
    customer: "Rajesh Kumar",
    designation: "Music Director",
    company: "Bollywood Productions",
    rating: 5,
    content: "Maheshwari Visuals has been instrumental in ...",
    status: "Published",
    createdAt: "2024-01-15",
  },
  {
    id: "2",
    customer: "Priya Sharma",
    designation: "Independent Artist",
    company: "Solo Artist",
    rating: 5,
    content: "The analytics and royalty management feature...",
    status: "Published",
    createdAt: "2024-02-20",
  },
  {
    id: "3",
    customer: "Mahesh Patel",
    designation: "Label Owner",
    company: "Classical Music Records",
    rating: 4,
    content: "Best music distribution platform I've used. The...",
    status: "Draft",
    createdAt: "2024-03-10",
  },
];
