// mockHelpSupportData.js

const HelpSupportData = {
  stats: {
    open: 2,
    pending: 1,
    resolved: 1,
    closed: 1,
  },
  tickets: [
    {
      id: "MVS-2024-001",
      user: "Rajesh Kumar",
      email: "rajesh@example.com",
      subject: "Upload issues with large audio files",
      category: "Technical",
      priority: "High",
      status: "Open",
      assignedTo: "Tech Team",
      created: "2024-03-15",
      responses: 0,
    },
    {
      id: "MVS-2024-002",
      user: "Maheshwari Music",
      email: "info@maheshwarimusic.com",
      subject: "Billing discrepancy in March invoice",
      category: "Billing",
      priority: "Medium",
      status: "Pending",
      assignedTo: "Finance Team",
      created: "2024-03-12",
      responses: 2,
    },
    {
      id: "MVS-2024-003",
      user: "Sound Aggregators",
      email: "contact@soundagg.com",
      subject: "Account verification pending",
      category: "Account",
      priority: "Medium",
      status: "Resolved",
      assignedTo: "Compliance Team",
      created: "2024-03-10",
      responses: 4,
    },
    {
      id: "MVS-2024-004",
      user: "Rajesh Kumar",
      email: "rajesh@example.com",
      subject: "Content takedown request",
      category: "Content",
      priority: "Critical",
      status: "Open",
      assignedTo: "Content Team",
      created: "2024-03-14",
      responses: 1,
    },
    {
      id: "MVS-2024-005",
      user: "Indie Artist Collective",
      email: "hello@indieartists.com",
      subject: "How to set up merchandise store?",
      category: "General",
      priority: "Low",
      status: "Closed",
      assignedTo: "Support Team",
      created: "2024-03-08",
      responses: 3,
    },
  ],
};

export default HelpSupportData;
